language: python
sudo: required

before_install:
  - sudo apt-get update        # Fetches the list of available updates
  - sudo apt-get upgrade       # Strictly upgrades the current packages
  - sudo apt-get dist-upgrade  # Installs updates (new ones)
  - sudo service docker restart
  - sleep 5

install:
  - sudo docker pull centos:centos6

script:
  - sudo docker build -t ${DOCKER_USERNAME}/${DOCKER_REPO} .

  # Deploy in script since docker isn't a provider
  - sudo docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
  - sudo docker push ${DOCKER_USERNAME}/${DOCKER_REPO}