language: python
sudo: required
python: "3.6"
before_install:
  - sudo cp /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 .
  - sudo cp /lib/x86_64-linux-gnu/libssl.so.1.0.0 .
  - sudo apt-get update
  - sudo apt-get install docker
  # setup a credential store for logging into docker hub
  - sudo apt-get install pass
  - curl -sO https://github.com/docker/docker-credential-helpers/releases/download/v0.6.0/docker-credential-pass-v0.6.0-amd64.tar.gz
  - export PATH=$PWD:$PATH
  - sudo service docker restart
  - sleep 5
  - sudo docker --version

install:
  - sudo docker pull centos:centos6

script:
  - sudo docker build -t ${DOCKER_USER}/${DOCKER_REPO} .
  - sudo docker images

  # Deploy in script since docker isn't a provider
  - sudo docker login --username=${DOCKER_USER} --password=${DOCKER_PASSWORD}
  - sudo docker push ${DOCKER_USER}/${DOCKER_REPO}